### PR TITLE
Add an option to store geometry as WKB, WKT or extent as WKT

### PR DESCRIPTION
**Pull request by mdouchin**
I have used WKT instead of GeoJSON.
I have not tested it yet, since I have not build QGIS 3 yet.
Can you please give it a try and report back any issue, while I am creating a vagrant box to build QGIS 3 ?

I also need to know what is your opinion regarding translation and the use of hard-coded texts 'wkb', 'wkt' and 'extent' in the combobox. If needed, I can add a "column" to separate the label and data for each option of geometryStorageCombo

### CODE REVIEW

**Comment by mdouchin** [comment]
I need to rebase against new master...

**Comment by mdouchin** [comment]
Need to replace "else if" by "elif" and check

**Comment by mdouchin** [comment]
Ok, I have created another branch from master_2 to test it under QGIS 2. I have some more fixes to do before having this PR ready. Stay tuned ;)

**Comment by mdouchin** [comment]
PR ready to test

**Comment by 3nids** [comment]
thanks a lot @mdouchin  
looking at it next week, sorry for the delay.

**Comment by mdouchin** [comment]
just corrected an issue, rebased, and repushed

**Comment by mdouchin** [comment]
Just added a (simple) migration system (for 3* and for 2* in other PR)
Please test on QGIS3 and report any issue

**Pull request merged**
