### PR TITLE
Add an option to store geometry as WKB, WKT or extent as WKT - Backport for master_2

### PR DESCRIPTION
**Pull request by mdouchin**

### CODE REVIEW

**Comment by mdouchin** [comment]
just corrected an issue, rebased, and repushed
This could be great to release a point fix version (last one) for QGIS 2.*.

**Comment by 3nids** [comment]
Was looking at the code.
Not tested yet, but it seems there is a compatibility issue.
You have a version in the dtabase see https://github.com/3nids/quickfinder/blob/master/core/project_finder.py#L43

There will be an error if using the new plugin with old version. 
Hence, whenever opening the FTS file (in ProjectFinder::setFile), there should be a check of the model version and an update if possible.

Can you handle this too?

**Comment by mdouchin** [comment]
Sure, will do it ( getting around the poor sqlite features for table structure modifications )

**Comment by mdouchin** [comment]
Hi @3nids Any update on this ? Please let me know if anything is needed

**Comment by 3nids** [comment]
Sorry for the delay. I had a look yesterday but had troubles with qgis 2. Will review by the end of the week. Sorry again

**Comment by 3nids** [comment]
thanks a lot!

**Pull request merged**
